environment: {}
parameters: {}
packages:
  - name: salesmen
    environment: {}
    parameters: {}
    annotations: {}
    actions:
      - name: salesmen
        binary: false
        main: "salesmen/salesmen.js"
        runtime: "nodejs:default"
        web: true
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}
